### ISSUE TITLE
Consider less restrictive license?

### ISSUE THREAD

**Issue by edemaine** [frangio/netlify-latex#6]
Nice work on this project!  I've just been adapting it to my project, and have a version that builds much faster (~2 minutes instead of ~10 minutes) that I can submit as a PR, relying more heavily on `texliveonfly`.

First I wanted to ask: would you consider a less-restrictive license compatible with MIT license?  I prefer to use MIT license for my open-source projects, so that people can use them however they like, and I'd like to include this build tool in a project I'm writing.  (Given that it's just used for a Netlify deployment, I'm not sure whether this tool would be considered "part of" my project or just a tool, and thus whether it needs to be under the same license... But relicensing netlify-latex would be clearest.)

**Comment by frangio** [comment]
Nice to hear that you've been able to optimize it! I'm a bit surprised by the 10 minutes that you mention. Last time I checked it was much much faster than that.

I would personally have no issue with an MIT licence, but as I mentioned in https://github.com/frangio/netlify-latex/issues/1#issuecomment-515175378 since this project is using (and distributing) `install-tl`, which is itself GPL licenced, I'm pretty sure this project has to be GPL licensed as well.

**Comment by edemaine** [comment]
Ah, fair point. [My refactor](https://github.com/edemaine/topp/blob/master/netlify-latex.sh) downloads `install-tl` instead of including it in the distribution, which I guess would circumvent this issue. The downside is that this would require clearing the cache to update `install-tl` versions; the upside is that it doesn't require any code modifications to update `install-tl` versions.

To summarize the changes I've made:
1. Removed `collection-binextra` and `collection-latex`, and instead `tlmgr install texliveonfly latex latex-bin` which was the minimum needed. (I also added `bibtex` because I need it.) This was where I was getting the speed improvement.  It's probably faster on Netlify; my times were on my own Linux machine with a slow disk (AFS).
2. Download `install-tl` instead of including it in repo. This could impact licensing, and makes it easy to upgrade `install-tl` versions (just clear Netlify cache).
3. For technical reasons, I wanted to use `pdflatex` and `bibtex`, not just `latexmk`. I added some command-line configurability for this, and could generalize it to be more useful. But I'm using this as an intermediate tool, not the final build step, so also don't have the `dist` copying. Perhaps factoring these into two tools would make sense?

I list these to ask: which would you like as PRs? I figure at least the first one is useful, but the others depend more on what features interest you. Perhaps I could add these features in a way that you have the choice of using them or not...

Back to licensing: perhaps you could offer just `netlify-latex.sh` under MIT license, in addition to offering the whole repo under GPL? I believe such dual-licensing is allowed, and would be useful in my case.

**Comment by frangio** [comment]
Okay the point about downloading is a good one. Reading from the [FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins):

>A main program that uses simple fork and exec to invoke plug-ins and does not establish intimate communication between them results in the plug-ins being a separate program.

I think `netlify-latex` qualifies as a separate program, thus it can be licensed under MIT.

I'm interested in PRs for points 1 and 2. Point 3 is interesting but I don't have a lot of time at the moment to review things so I would prioritize the others.

If you would like to make these contributions (thank you so much!) I would be happy to license as MIT once `install-tl` is downloaded instead of vendored in.

**Comment by edemaine** [comment]
Thanks for the feedback! I implemented points 1 and 2 in #7 and #8.

Maybe better to think of point 3 as a fork (more of a Netlify script than a template)... I'll let you know if I release it as a stand-alone thing, or see a way to turn it into a PR.

I agree with your reading of the FAQ -- cool! Once `install-tl` isn't included in the repo/template anymore, this seems especially clear. Thanks for your willingness and responsiveness!

**Comment by frangio** [comment]
I've now relicensed this project as MIT.

Thank you for the PRs again and sorry for the delay in merging!
